### ISSUE TITLE
Update DNS record

### ISSUE THREAD

**Issue by jenmontes** [tricknotes/nothub.org#3]
The http://nothub.org/ website is currently showing the GitHub error message below.

---
# Site disabled · GitHub Pages

**Oh no! It looks like this Pages site has been disabled due to a misconfigured custom domain.**

_Are you the site owner?_ You can quickly fix this issue by updating the DNS record for your Pages site:

* If you're using a subdomain (coolthing.example.com, www.example.com, etc.), make sure you have a **CNAME** record that points to **your-username.github.io**.
* If you're not using a subdomain (example.com), make sure you have two **A** records set to the following IPs: **192.30.252.153** and **192.30.252.154**

More detailed instructions for [setting up a custom domain with GitHub pages][1] are also available if you need more guidance.

You can find more information about these changes in our [GitHub Pages legacy IP deprecation][2] blog post. If you have any questions, please [contact support][3].

[1]: https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/
[2]: https://github.com/blog/1917-github-pages-legacy-ip-deprecation
[3]: https://github.com/contact

**Comment by tricknotes** [comment]
Good catch.
I set a new IPs to `nothub.org`. Now it seems fixed.

Thanks! You're such a great person :whale: :whale: :whale:
